version: 0.2

env:
  variables:
    REACT_APP_API_URL: 'http://lof-server.us-west-1.elasticbeanstalk.com'

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd lof-client
      - yarn install
  build:
    commands:
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: 'lof-client'
