version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd lof-server
      - yarn install --production
artifacts:
  files:
    - '**/*'
  base-directory: 'lof-server'

